# As the org-agent, this file documents the agent-task-pipeline.
# This pipeline is central to the framework's task management and knowledge organization.
# It automates the initial processing and organization of new tasks and updated files.
pipeline:
  name: "agent-task-pipeline"
  trigger: ["task.created", "file.updated"]

  steps:
    - agent: docbot
      on: ["README*", "*.md"]

    - agent: structurekeeper
      on: ["*.json", "*/"]

    - agent: typemapper
      on: ["*.yaml", "*.yml"]

    - agent: taskrouter
      on: ["tasks/*.json"]

    - agent: conceptweaver
      on: ["concepts/**"]

    - agent: indexer
      on: ["**/*"]