name: release-diff-pipeline
description: Generate release package using only modified files since last tag
trigger: manual

steps:
  - id: capture_modified_files
    name: Capture Modified Files
    run: |
      git fetch --tags
      LAST_TAG=$(git describe --tags --abbrev=0)
      git diff --name-only $LAST_TAG..HEAD > .release-changes.txt
      echo "Modified files since $LAST_TAG:"
      cat .release-changes.txt

  - id: generate_diff_zip
    name: Generate Diff Release Zip
    run: |
      VERSION=$(cat version-manifest-v0.23.0-pre.json | jq -r .version)
      zip -r release-$VERSION-diff.zip -@ < .release-changes.txt

  - id: finalize_output
    name: Output Release Artifact
    output: release-$(cat version-manifest-v0.23.0-pre.json | jq -r .version)-diff.zip